### ISSUE TITLE
Expired certificate on demo.malice.io

### ISSUE THREAD

**Issue by zwass** [maliceio/malice#107]
Your cert expired 2019-10-14.

<img width="1140" alt="Screen Shot 2020-02-22 at 9 55 39 PM" src="https://user-images.githubusercontent.com/575602/75104470-2b7d4a80-55be-11ea-9799-b257c2fd9d52.png">

**Comment by blacktop** [comment]
Fixed thank you! I don't know why the certbot cron job always seems to fail? 😭

**Comment by DanielRuf** [comment]
It seems the server / website is not available anymore.

**Comment by DanielRuf** [comment]
Hm, seems this is not yet the case for https://malice.io/.
Thanks for the fast reply, it seems https://demo.malice.io/ works now (I can see the kibana login).

**Comment by blacktop** [comment]
ah so malice.io is down for now it was meant to be a home site for malice, but for now the README is the home

**Comment by DanielRuf** [comment]
Ah ok, understood.
