### ISSUE TITLE
Cannot install  malice

### ISSUE THREAD

**Issue by andr6** [maliceio/malice#27]
**Output of `go version`:**

```
go version go1.6 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-69-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 11.73 GiB
Name: cuckoo-001
ID: NTPM:YTBN:DGZN:CYC6:PRTO:IVJV:QIH7:B2BB:UHPM:7IPM:UUIM:3MUE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

Ubuntu 14.04.5 LTS \n \l

**Describe the results you received:**

go get github.com/maliceio/malice
package context: unrecognized import path "context" (import path does not begin with hostname)

Installation failing .

**Comment by blacktop** [comment]
There was a change back I think in go 1.6.3 or go 1.7 that changed the way the `context` package worked and was imported.  Can you please try with go 1.7.1?  I updated the install docs to reflect this as well [here](https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md)

Thank you for reporting this :)

**Comment by blacktop** [comment]
Also just as a FYI, if you don't want to install go or the malice binary, once you install docker you can just run this single command to install malice and all of it's default plugins:

```bash
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock malice/engine plugin update --all
```

The only downside is running scans requires more typing, but you could fix that with an alias like this:

```bash
$ alias malice='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
                -v `pwd`:/malice/samples \
                -e MALICE_VT_API=$MALICE_VT_API \
                malice/engine $@'
```

😎

**Comment by andr6** [comment]
Thanks. Seems that installation is now successful. 

Probably the install manual should also include the correct path to call go for install otherwise it will use the system go. 

/usr/local/bin/go get -v github.com/maliceio/malice

Cheers

**Comment by blacktop** [comment]
Glad I could help.

**Comment by vmorgo** [comment]
Did what you suggested in the following on Mate 18.02 "Sonya".  Worked a treat, except that the version of ElasticSearch that docker pulled seems to be too old.  Kibana fails with:

"This version of Kibana requires Elasticsearch v5.4.3 on all nodes. I found the following incompatible nodes in your cluster: v5.3.3"

Any help or advice would be appreciated.  If you need it, here's the result of docker info:

Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.10.0-27-generic
Operating System: Linux Mint 18.2
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.857 GiB
Name: domcr-kvm-malice
ID: X6GQ:6IPA:O3DC:LZ4W:ANVG:LSZL:OQJ4:DN72:PRKN:EP52:G5RS:CIPP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

Many thanks!

A./

**Comment by blacktop** [comment]
what version of malice are you running?

I recently updated the versions of elasticsearch/kibana that malice uses to their own new repos `malice/elasticsearch` and `malice/kibana` that way it will be easier to keep them insync.

**Comment by blacktop** [comment]
if you are using an older version of malice that might cause it.  If you upgrade malice should ask if you want to upgrade to the new config that uses the new repos.  If not you might want to uninstall/re-install (remember to remove ~/.malice as that i where the old config will be)

**Comment by vmorgo** [comment]
Moved to the stand-alone executable, which seems to work mostly.  (Please close other ticket with complaint about the request to update the config file.  I'll rebuild the VM and try that again.  I had forgotten to remove the docker version I had originally installed, and which did NOT work.

The stand-alone executable does NOT seem to be able to work properly with Elk.  You mentioned the possibility of upgrading the configuration file.

I also tried "malice install [arg...]" as malice suggests, e.g., "malice install malice/kibana" or "malice install kibana", but the response is to be told "'install' is not a malice command."  "malice plugin install kibana" also produces no discernible result--no feedback, either.

"Malice elk" does not work, but, again, instructions on how to configure it to properly pull the proper version of elasticsearch and kibana:malice would be helpful.  So far, the only result I can get is the following dumpage:

(Current version of malice stand-alone seems to be simply marked "dev" without any number.  It still seems to want to run some sort of docker container for Elasticsearch:5.3.)

ERRO[0000] Container is already running...               env=development exisits=true name=malice-elastic
ERRO[0000] container is already running                 
Pulling repository docker.io/blacktop/kibana
ERRO[0000] CreateContainer error = Error: No such image: blacktop/kibana:malice
  env=development
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556ab5eb9883]

goroutine 1 [running]:
panic(0x556ab6619980, 0xc420012050)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/maliceio/malice/malice/docker/client/container.Start(0xc42037eb40, 0x0, 0x0, 0x0, 0xc420319af0, 0xd, 0xc4203222a0, 0x16, 0x556ab5d9f500, 0x0, ...)
	/go/src/github.com/maliceio/malice/malice/docker/client/container/start.go:74 +0x4c3
github.com/maliceio/malice/malice/ui.Start(0xc42037eb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/maliceio/malice/malice/ui/ui.go:32 +0x272
github.com/maliceio/malice/commands.cmdELK(0xc4202d9900, 0x556ab628e05b, 0x4)
	/go/src/github.com/maliceio/malice/commands/elk.go:19 +0x9b
github.com/maliceio/malice/commands.glob..func4(0xc4202d9900, 0x0, 0xc4202d9900)
	/go/src/github.com/maliceio/malice/commands/commands.go:69 +0x4f
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x556ab65f0660, 0x556ab66d3e00, 0xc4202d9900, 0xc420330000, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x556ab628d893, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x556ab629e4fd, 0x1e, 0x0, ...)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc42009b860, 0xc42000c120, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
	/go/src/github.com/maliceio/malice/main.go:88 +0x54a

**Comment by blacktop** [comment]
it looks like it is still trying to use the old kibana `blacktop/kibana:malice`  please tell me what is here: `~/.malice/config/config.toml`

**Comment by blacktop** [comment]
did you get the binary version from the latest release? https://github.com/maliceio/malice/releases/tag/v0.3.11

**Comment by blacktop** [comment]
the docker version of malice is broken because of docker's switch to moby which broke my dependancies.  I am working on bringing it back with the malice re-write (not ready to use yet) that is happening here: https://github.com/maliceio/engine

**Comment by blacktop** [comment]
I just downloaded the binary into a linux VM and it wasn't `version:dev` it was `0.3.11` I am not sure what it going on with your set up.
