### ISSUE TITLE
Plugin install failing Ubuntu 14.04

### ISSUE THREAD

**Issue by andr6** [maliceio/malice#29]
**Output of `go version`:**

```
go version go1.7.1 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 13
 Running: 1
 Paused: 0
 Stopped: 12
Images: 27
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 128
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.842 GiB
Name: malice
ID: P7KN:S3HU:SXY3:RG45:FFVN:6XFG:RG4X:FL5T:IZ3Z:Q4G3:2XTT:WR3E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```
**Steps to reproduce the issue:**
1. malice plugin update --all

**Describe the results you received:**

Running hooks in /etc/ca-certificates/update.d....done.
.+ set -x
.+ echo Install F-PROT...
.+ tar -C /opt -zxvf /go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
Install F-PROT...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

/var/lib/docker/aufs/diff/13606656ea9e840002d158b03ab10e12b7d8475488a082cd40e81c0316914b6e/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/4074f24c1deefc648e24774d894f9c9cec34c791782cf935f3e4dee2021f62b5/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/604cce9e6f6d6962139c5f014ba3104abf28746ae9f04fbd1f8a0d713606ff7a/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/6d25119dd51e190a8aac6858dfc2ff5d32d087acb1af8c94f55a85765a5e9257/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/791cad2ef84f3ed5b142a0e20550fd0afff16e5cfad98b6a1258ab9da88ba4f7/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
root@malice:/opt# file /var/lib/docker/aufs/diff/13606656ea9e840002d158b03ab10e12b7d8475488a082cd40e81c0316914b6e/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/13606656ea9e840002d158b03ab10e12b7d8475488a082cd40e81c0316914b6e/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz: ASCII text
root@malice:/opt# file /var/lib/docker/aufs/diff/4074f24c1deefc648e24774d894f9c9cec34c791782cf935f3e4dee2021f62b5/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/4074f24c1deefc648e24774d894f9c9cec34c791782cf935f3e4dee2021f62b5/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz: ASCII text
root@malice:/opt# file /var/lib/docker/aufs/diff/604cce9e6f6d6962139c5f014ba3104abf28746ae9f04fbd1f8a0d713606ff7a/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/604cce9e6f6d6962139c5f014ba3104abf28746ae9f04fbd1f8a0d713606ff7a/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz: ASCII text
root@malice:/opt# file /var/lib/docker/aufs/diff/6d25119dd51e190a8aac6858dfc2ff5d32d087acb1af8c94f55a85765a5e9257/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/6d25119dd51e190a8aac6858dfc2ff5d32d087acb1af8c94f55a85765a5e9257/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz: ASCII text
root@malice:/opt# file /var/lib/docker/aufs/diff/791cad2ef84f3ed5b142a0e20550fd0afff16e5cfad98b6a1258ab9da88ba4f7/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz
/var/lib/docker/aufs/diff/791cad2ef84f3ed5b142a0e20550fd0afff16e5cfad98b6a1258ab9da88ba4f7/go/src/github.com/maliceio/malice-fprot/fp-Linux.x86.32-ws.tar.gz: ASCII text

output of the files:  
version https://git-lfs.github.com/spec/v1
oid sha256:aad50674ea3657894b5f9a11a7f3cdb476638c5e43c95a7a26f62ebe565083e1
size 30914110

**Comment by blacktop** [comment]
Do you have git-lfs enabled? https://git-lfs.github.com

I don't think people should have to have that enabled to work and will fix it, but I am curious if that is the issue or not.

**Comment by blacktop** [comment]
I changed the f-prot av plugin so it shouldn't fail now.  I greatly appreciate your help.  Let me know if the problem is fixed on your end.

**Comment by andr6** [comment]
[Updating Plugin] ===>  fprot
INFO[0333] [Building Plugin from Source] ===> fprot
