### ISSUE TITLE
Cannot install Malice in Ubuntu 16.04.1

### ISSUE THREAD

**Issue by nikben** [maliceio/malice#32]
**Output of `go version`:**

```
go version go1.6.2 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: kalxas
ID: VTAX:V47H:7DMS:TYKW:GGM3:Y5OK:IA3F:4WSJ:TJNW:QOEE:CCMI:4WUG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**

VM inside ESXi 

**Steps to reproduce the issue:**
1. Followed installation instructions for linux as mentioned here: https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md
2. OS is Ubuntu 16.04.1 LTS Xenial (I know instructions are for Ubuntu 14.04.3)
3. Added this in .bashrc and .profile:
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
4.  Issue occurs in this step: go get -v github.com/maliceio/malice

**Describe the results you received:**
$ go get -v -u github.com/maliceio/malice
github.com/maliceio/malice (download)
package context: unrecognized import path "context" (import path does not begin with hostname)
Fetching https://golang.org/x/crypto/ed25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519?go-get=1
get "golang.org/x/crypto/ed25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519/internal/edwards25519": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
get "golang.org/x/crypto/ed25519/internal/edwards25519": verifying non-authoritative meta tag

**Describe the results you expected:**
Install Malice

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by blacktop** [comment]
Malice requires Go 1.7+.  There are instructions on how to install Go 1.7.1 on Ubuntu here: https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md#install-go

**Comment by nikben** [comment]
Thanks for the reply. I'll try it!!!
