### ISSUE TITLE
Cannot Disable Plugin

### ISSUE THREAD

**Issue by andr6** [maliceio/malice#33]
@blacktop Trying to remove the offender plugin on ticket #30 - shadow-server.

Deleting the plugin does not work .

root@malice:~# malice plugin list
virustotal
shadow-server
fileinfo
yara
avg
bitdefender
clamav
comodo
fprot
f-secure
sophos
floss
root@malice:~# malice plugin remove shadow-server
root@malice:~# malice plugin list
virustotal
shadow-server
fileinfo
yara
avg
bitdefender
clamav
comodo
fprot
f-secure
sophos
floss
root@malice:~#

**Comment by blacktop** [comment]
FYI Another way to remove/disable plugins in the manually change them in `~/.malice/plugins.toml`
