### ISSUE TITLE
bug in the switch to Elasticsearch 5.0.1

### ISSUE THREAD

**Issue by blacktop** [maliceio/malice#40]
```bash
~/s/g/d/2.5 git:master ❯❯❯ malice lookup 6fe80e56ad4de610304bab1675ce84d16ab6988e

2016/11/23 10:49:06 elastic: Error 400 (Bad Request): Validation Failed: 1: an id must be provided if version type or value are set; [type=action_request_validation_exception]
```

Is expecting a **ID** for lookups where they should be auto generated

**Comment by blacktop** [comment]
was fixed

**Comment by wanhl1990** [comment]
Get the save error

info

`
[root@test ~]# malice --version
malice version 0.3.11, commit 9e7f91e08345f227b4ddfe3690bc5ee52d1c6feb, built at 2017-07-22T23:52:36Z
[root@test~]# 

[root@test~]# docker ps 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                              NAMES
9588cff65960        malice/kibana:5.5          "/docker-entrypoin..."   5 hours ago         Up 5 hours          0.0.0.0:80->5601/tcp               malice-kibana
1000e9655541        malice/elasticsearch:5.5   "/elastic-entrypoi..."   5 hours ago         Up 5 hours          0.0.0.0:9200->9200/tcp, 9300/tcp   malice-elastic
[root@test~]# 
`
