### ISSUE TITLE
Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused

### ISSUE THREAD

**Issue by fbarre96** [maliceio/malice#43]
**Output of `go version`:**

```
go version go1.7.1 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 21
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 142
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.597 GiB
Name: debian
ID: 6G3A:VAFC:U2R7:T7YQ:MXFG:JFPV:RJQC:WT74:ZUWF:EI7P:RZEB:CWR2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**
The installation worked except for avast plugin. I tried to restart the docker elk but know I get this error
Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused.
It's probably something really dumb though...

**Steps to reproduce the issue:**
1. docker stop malice-elk
2. malice elk start
3. malice -D scan ~/go/bin/malice

**Describe the results you received:**
DEBU[0000] Malice config loaded from: /home/algosecure/.malice/config.toml 
DEBU[0000] Malice plugins loaded from: /home/algosecure/.malice/plugins.toml 
DEBU[0000] Using 2 PROCS                                
DEBU[0000] Malice Version: 0.2.0-alpha                  
DEBU[0000] Running inside Docker...                     
DEBU[0000] Connected to docker daemon client             ip=localhost port=2375
DEBU[0000] Searching for container: malice-elk           env=development
DEBU[0000] name:  malice-elk   container.Name:  loving_mccarthy 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elk   container.Name:  cocky_lumiere 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elk   container.Name:  objective_kalam 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elk   container.Name:  modest_stallman 
DEBU[0000] MATCH:  false                                
DEBU[0000] name:  malice-elk   container.Name:  malice-elk 
DEBU[0000] MATCH:  true                                 
DEBU[0000] Container FOUND: malice-elk                   env=development
DEBU[0000] ELK is running.                               image=blacktop/elastic-stack:malice ip= network=default
DEBU[0000] Attempting to connect to: http://localhost:9200 
2017/02/06 12:01:36 Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused

**Describe the results you expected:**
A normal scan with avast not working

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by blacktop** [comment]
I like that you are scanning the malice binary with malice I haven't thought to try that yet 😉

**Comment by blacktop** [comment]
This might be related to #39. I have noticed that the `blacktop/elastic-stack:malice` takes a little while to fully boot so I tried to be clever and wait-for-it in golang, but it seems to be exiting once it sees it is running the very first time.  Can you do a:

```bash
docker ps -a
```

To see what state malice-elk is in?

Thank you

**Comment by blacktop** [comment]
You can also do a `docker rm -f malice-elk` to clear it out, the data should persist to the malice docker volume.

**Comment by fbarre96** [comment]
Thank you, the last command worked! For those who have the same issue : rm -f malice-elk and then malice elk

I'll just have to figure out how to install avg
