### ISSUE TITLE
Fix Elasticsearch

### ISSUE THREAD

**Issue by blacktop** [maliceio/malice#47]
TODO

 - [x] fix plugin communication to ES
 - [x] wait for ES to fully start (not just a dumb 10 sec wait)
 - [x] monitor logs to output important info as to why it might not start (not enough RAM etc)
 - [ ] auto populate kibana index/viz/dashboards like how a file-beat module does it
 - [x] add `~/.malice/logs/elastic.log` to catch ES errors

**Comment by vmorgo** [comment]
Docker (or whatever) still pulling ElasticSearch 5.3.  We need 5.4 or better, 5.5.  Not possible to edit ~/.malice/config/config.toml to change this as all attempts to edit this file are overwritten with the original (incorrect) information when we start Malice.

**Comment by blacktop** [comment]
are you using the latest version? https://github.com/maliceio/malice/releases/download/v0.3.11/malice_0.3.11_linux_amd64.tar.gz

**Comment by blacktop** [comment]
this is a project goal not an issue
