### ISSUE TITLE
ERRO[0021] Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused

### ISSUE THREAD

**Issue by nakagit** [maliceio/malice#50]
**Output of `go version`:**

```
go version go1.7.4 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:1-49557999-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.588 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.79 GB
 Metadata Space Used: 7.213 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.9.0-kali3-amd64
Operating System: Kali GNU/Linux Rolling
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.783 GiB
Name: kali20171
ID: A3QN:QDEP:FKCB:OZHO:FHMA:2RTS:ZCLV:O7ZG:QPRS:TFOI:IMBT:4D7I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**
Kali Linux 2017.1 (64bit), Memory: 8GB

**Steps to reproduce the issue:**
1. apt-get update
2. cd /etc/apt/sources.list.d/
3. gedit backports.list &
 add 1 line: 
 deb http://http.debian.net/debian wheezy-backports main

4. apt-get update
5. apt-get install apt-transport-https ca-certificates gnupg2 dirmngr
6. apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

7. gedit /etc/apt/sources.list.d/docker.list &
 add 1 line:
 deb https://apt.dockerproject.org/repo debian-jessie main

8. apt-get update
9. apt-cache policy docker-engine
10. apt-get install docker-engine=1.12.5-0~debian-jessie
11. usermod -aG docker $USER
12. apt-get install golang
13. cd
14. gedit .bashrc &
 add 2 lines at the bottom:
export GOPATH=$HOME 
export PATH=$PATH:$GOPATH/bin

15. source .bashrc
16. cd /opt
17. wget https://github.com/maliceio/malice/releases/download/v0.2.0-alpha/malice_0.2.0-alpha_linux_amd64.zip -O /tmp/malice.zip
18. unzip /tmp/malice.zip -d /usr/local/bin/
19. malice plugin update --all
20. malice plugin list --all --detail
21. systemctl enable docker
22. malice elk

**Describe the results you received:**
# malice elk
ERRO[0000] Network malice does not exist, creating now...  env=development exisits=false network=malice
INFO[0000] Created Network: malice                       env=development name=malice
INFO[0000] Created Volume: malice                        env=development
INFO[0001] Elasticsearch Container Started               env=development ip=localhost name="/malice-elastic" port=[9200]
INFO[0001] Waiting for Elasticsearch to come online.     server="http://localhost:9200" timeout=20
ERRO[0021] connecting to elasticsearch timed out         timeout=20
ERRO[0021] Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused 
ERRO[0021] Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused 
malice: Pulling from blacktop/kibana
627beaf3eaaf: Already exists 
0c8e9a12d743: Pull complete 
3fab1effe157: Pull complete 
d6d275309877: Pull complete 
9b7f57263aaf: Pull complete 
Digest: sha256:3c069a0ec9f046d7853d53f67075c77dabdb17ac363dac72a1a11b8d20ea4e56
Status: Downloaded newer image for blacktop/kibana:malice
ERRO[0038] StartContainer error = Error response from daemon: Cannot link to a non running container: /malice-elastic AS /malice-kibana/elasticsearch
  env=development
INFO[0038] Kibana Container Started                      env=development ip=localhost name="/malice-kibana" port=[443]

**Describe the results you expected:**
I think Elasticsearch container didn't start properly. 

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

Kindest regards,
YN (nakagit)

**Comment by blacktop** [comment]
Can you try the latest version: https://github.com/maliceio/malice/releases/download/v0.3.2/malice_linux_amd64.tar.gz

**Comment by nakagit** [comment]
Thank you for your comments(advice). But, I'm afraid the same error occurred.

Error messages are following:
ERRO[0000] Network malice does not exist, creating now...  env=development exisits=false network=malice
INFO[0000] Created Network: malice                       env=development name=malice
INFO[0000] Created Volume: malice                        env=development
INFO[0000] Elasticsearch Container Started               env=development ip=localhost name="/malice-elastic" port=[9200]
INFO[0000] Waiting for Elasticsearch to come online.     server="http://localhost:9200" timeout=20
ERRO[0021] connecting to elasticsearch timed out         timeout=20
ERRO[0021] Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused 
ERRO[0021] Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused 
malice: Pulling from blacktop/kibana
627beaf3eaaf: Already exists 
0c8e9a12d743: Pull complete 
3fab1effe157: Pull complete 
d6d275309877: Pull complete 
9b7f57263aaf: Pull complete 
Digest: sha256:3c069a0ec9f046d7853d53f67075c77dabdb17ac363dac72a1a11b8d20ea4e56
Status: Downloaded newer image for blacktop/kibana:malice
ERRO[0039] StartContainer error = Error response from daemon: Cannot link to a non running container: /malice-elastic AS /malice-kibana/elasticsearch
  env=development
INFO[0039] Kibana Container Started                      env=development ip=localhost name="/malice-kibana" port=[443]

Regards,
YN

**Comment by blacktop** [comment]
what do you see when you `docker logs malice-elastic`

**Comment by blacktop** [comment]
Also have you done this? https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md#fix-elasticsearch

**Comment by nakagit** [comment]
When I executed 'docker logs malice-elastic':

# docker logs malice-elastic
[2017-04-27T03:16:41,885][INFO ][o.e.n.Node               ] [] initializing ...
[2017-04-27T03:16:41,980][INFO ][o.e.e.NodeEnvironment    ] [f7zaet_] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [915.9gb], net total_space [981.3gb], spins? [possibly], types [ext4]
[2017-04-27T03:16:41,981][INFO ][o.e.e.NodeEnvironment    ] [f7zaet_] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-04-27T03:16:41,983][INFO ][o.e.n.Node               ] node name [f7zaet_] derived from node ID [f7zaet__Syma2ok_JhzD8A]; set [node.name] to override
[2017-04-27T03:16:41,983][INFO ][o.e.n.Node               ] version[5.3.1], pid[1], build[5f9cf58/2017-04-17T15:52:53.846Z], OS[Linux/4.9.0-kali3-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [aggs-matrix-stats]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [ingest-common]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [lang-expression]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [lang-groovy]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [lang-mustache]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [lang-painless]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [percolator]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [reindex]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [transport-netty3]
[2017-04-27T03:16:42,809][INFO ][o.e.p.PluginsService     ] [f7zaet_] loaded module [transport-netty4]
[2017-04-27T03:16:42,810][INFO ][o.e.p.PluginsService     ] [f7zaet_] no plugins loaded
[2017-04-27T03:16:44,725][INFO ][o.e.n.Node               ] initialized
[2017-04-27T03:16:44,725][INFO ][o.e.n.Node               ] [f7zaet_] starting ...
[2017-04-27T03:16:44,842][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 22:cb:e1:18:39:76:14:74
[2017-04-27T03:16:44,925][INFO ][o.e.t.TransportService   ] [f7zaet_] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
[2017-04-27T03:16:44,930][INFO ][o.e.b.BootstrapChecks    ] [f7zaet_] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-04-27T03:16:44,972][INFO ][o.e.n.Node               ] [f7zaet_] stopping ...
[2017-04-27T03:16:45,062][INFO ][o.e.n.Node               ] [f7zaet_] stopped
[2017-04-27T03:16:45,062][INFO ][o.e.n.Node               ] [f7zaet_] closing ...
[2017-04-27T03:16:45,078][INFO ][o.e.n.Node               ] [f7zaet_] closed

**Comment by nakagit** [comment]
Sorry, I didn't following Elasticsearch workaround:
https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md#fix-elasticsearch

I'll test with v0.3.2 and above Elasticsearch workaround. Then, I'll let you know results.

Many thanks,
YN

**Comment by nakagit** [comment]
Thank you very, very, very much. It worked.  I mean you fix the problem as following:

root@kali20171:# more /etc/sysctl.conf|grep -i vm.max
vm.max_map_count=262144
root@kali20171:# malice elk
ERRO[0000] Network malice does not exist, creating now...  env=development exisits=false network=malice
INFO[0000] Created Network: malice                       env=development name=malice
INFO[0000] Created Volume: malice                        env=development
INFO[0000] Elasticsearch Container Started               env=development ip=localhost name="/malice-elastic" port=[9200]
INFO[0000] Waiting for Elasticsearch to come online.     server="http://localhost:9200" timeout=20
INFO[0019] Elasticsearch came online after 18 seconds   
malice: Pulling from blacktop/kibana
627beaf3eaaf: Already exists 
0c8e9a12d743: Pull complete 
3fab1effe157: Pull complete 
d6d275309877: Pull complete 
9b7f57263aaf: Pull complete 
Digest: sha256:3c069a0ec9f046d7853d53f67075c77dabdb17ac363dac72a1a11b8d20ea4e56
Status: Downloaded newer image for blacktop/kibana:malice
INFO[0038] Kibana Container Started                      env=development ip=localhost name="/malice-kibana" port=[443]

Kindest regards,  :)  👍 
YN

**Comment by nakagit** [comment]
Thanks again.

**Comment by nakagit** [comment]
May I close this issue?

**Comment by blacktop** [comment]
I'm glad I could help and thank you for trying **malice**.  This is your issue, you can close when ever you want 😉

**Comment by nakagit** [comment]
Thank you very much again.  :)  👍
