### ISSUE TITLE
Problem with ElasticSearch/Elk

### ISSUE THREAD

**Issue by vmorgo** [maliceio/malice#52]
**Output of `go version`:**

```
go version go1.7.1 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-87-generic
Operating System: Linux Mint 18.1
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: kvm-malice
ID: DAXD:ZCFT:CVPK:5GQ5:XTYW:MKRN:WWEK:LQSF:DMZC:YR37:F5DK:OOD4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
  (The running container is malice-elastic, version 5.3.)
```

Using standard pre-compiled binary on Linux Mint 18.1 "Serena", Mate version with all current updates.  This is a KVM virtual machine running on an Ubuntu-based host. 4 GB RAM, 4 cores.

**Steps to reproduce the issue:**
1. Install precompiled binary.  Run malice plugins update --all.
2.  Answer prompt "Newer version of malice config.toml available:  Version 0.3.2" with "yes"
Repeat step two two or three times, as you will be prompted the same thing three times.  Even though this is already malice 0.3.2.
3. Try to execute "malice elk".

**Describe the results you received:**
ERRO[0002] Container is already running...               env=development exisits=true name=malice-elastic
ERRO[0002] container is already running                 
Pulling repository docker.io/blacktop/kibana
ERRO[0003] CreateContainer error = Error: No such image: blacktop/kibana:malice
  env=development
ERRO[0003] StartContainer error = Error response from daemon: page not found
  env=development
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84b168]

goroutine 1 [running]:
github.com/maliceio/malice/malice/docker/client/container.Start(0xc4203c6cc0, 0x0, 0x0, 0x0, 0xc42035d520, 0xd, 0xc42035bba0, 0x16, 0x0, 0x0, ...)
	/Users/blacktop/go/src/github.com/maliceio/malice/malice/docker/client/container/start.go:74 +0x468
github.com/maliceio/malice/malice/ui.Start(0xc4203c6cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/blacktop/go/src/github.com/maliceio/malice/malice/ui/ui.go:32 +0x29e
github.com/maliceio/malice/commands.cmdELK(0xc4202e3b00, 0xab9120, 0x4)
	/Users/blacktop/go/src/github.com/maliceio/malice/commands/elk.go:19 +0xdb
github.com/maliceio/malice/commands.glob..func4(0xc4202e3b80, 0x0, 0xc4202e3b80)
	/Users/blacktop/go/src/github.com/maliceio/malice/commands/commands.go:69 +0x4d
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x9c9220, 0xade000, 0xc4202e3b80, 0xc420334700, 0x0)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0xab899e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xac9777, 0x1e, 0x0, ...)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc4202cc9c0, 0xc42000a200, 0x2, 0x2, 0x0, 0x0)
	/Users/blacktop/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/Users/blacktop/go/src/github.com/maliceio/malice/main.go:88 +0x584

**Describe the results you expected:**
Expected the web interface "Elk", presumably ElasticSearch + Kibana, to start.
In other examples, e.g., running docker version of malice within docker, I did get a Kibana package, but it would not run as it complained that ElasticSearch 5.4.3 was expected, but only version 5.3 was found "on all nodes".

Scanning function seems to work rather well.  :)

**Additional information you deem important (e.g. issue happens only occasionally):**
Bug(s) are 100% reproducible.

**Comment by vmorgo** [comment]
Please let me know if I can provide any further information.

**Comment by blacktop** [comment]
can you tell me what is in this file `~/.malice/config/config.toml` in that file you can also manually change it to use the newer elasticsearch/kibana version

**Comment by blacktop** [comment]
I talk about how to change the config here too - https://github.com/maliceio/malice-kibana-plugin/issues/4#issuecomment-315658581
