### ISSUE TITLE
Output in json format 

### ISSUE THREAD

**Issue by dsslimshaddy** [maliceio/malice#56]
Instead of extracting from markdown. is there any way to get the output in json format ?

Its actually a great piece of software its just missing this one important thing i guess.

**Comment by blacktop** [comment]
There will be in the new version of malice I am building here - https://github.com/maliceio/engine, but for now the way to get JSON is to pull it out of Elasticsearch so you would scan the file which would output Markdown to stdOut, but then you could do:

```bash
$ echo '{
  "query": {
    "term": {
      "file.sha256": "befb88b89c2eb401900a68e9f5b78764203f2b48264fcc3f7121bf04a57fd408"
    }
  }
}' | http GET :9200/malice/samples/_search
```

To get the results as JSON for the sample `befb88b89c2eb401900a68e9f5b78764203f2b48264fcc3f7121bf04a57fd408`

**Comment by dsslimshaddy** [comment]
`http: error: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /malice/samples/_search (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbe5cdcf810>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by blacktop** [comment]
hmmm this tells me you aren't running elasticsearch on localhost (the default for OSX) on linux you can get the IP/host from this command: 

`$ ifconfig docker0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

**Comment by blacktop** [comment]
or if you are running on amazon it would be your elasticIP/the domain

**Comment by dsslimshaddy** [comment]
just because of #57 elastic search wasnt running. so its not an issue anymore
