### ISSUE TITLE
"Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused"

### ISSUE THREAD

**Issue by draske79** [maliceio/malice#64]
**Output of `go version`:**

```
go version go1.6.2 linux/amd64
```

**Output of `docker version`:**

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:40 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 20
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: localhost.localdomain
ID: J3ZY:ZUU7:SW6Y:QTFY:6LUH:LFYF:7NVD:J2AO:2YW4:55K6:G252:DT3A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**

Clean ubuntu 16.04 install on dedicated server. Only Malice is installed according instructions. I reinstalled the server several times, once with a ubuntu 14 version with the same result. It is is probably something stupid I am missing but it drives me crazy

**Steps to reproduce the issue:**
1. Install malice according to instructions
2. Run the plugin update. No errors
3. Run the first scan, everything is fine (malice scan sample.exe)
4. Reboot the system
5. Now when I run a scan it fails with the error below

Results:

ERRO[0000] "Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused"
goroutine 1 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0xdf02a0, 0xc420329d10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x7d
github.com/maliceio/malice/malice/errors.CheckError(0xdf02a0, 0xc420329d10, 0xc4203ae200)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
github.com/maliceio/malice/malice/database/elasticsearch.InitElasticSearch(0x0, 0x0, 0x1, 0x1)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/database/elasticsearch/elasticsearch.go:124 +0x68
github.com/maliceio/malice/commands.ScanSample(0x7ffdb3b7e841, 0xe)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:58 +0x46f
github.com/maliceio/malice/commands.cmdScan(0x7ffdb3b7e841, 0xe, 0x0, 0xc420380000, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:22 +0x35
github.com/maliceio/malice/commands.glob..func1(0xc4202f7680, 0x0, 0xc4202f7680)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/commands.go:25 +0x8a
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x9c9220, 0xade028, 0xc4202f7680, 0xc420380000, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0xab9204, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xabcf9f, 0xb, 0x0, ...)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc42005dba0, 0xc420074090, 0x3, 0x3, 0x0, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
        /Users/user/src/go/src/github.com/maliceio/malice/main.go:88 +0x584

2018/03/17 20:23:18 Head http://localhost:9200/malice: dial tcp [::1]:9200: getsockopt: connection refused

**Additional information you deem important (e.g. issue happens only occasionally):**

I do not get the system working again until a system reinstall of ubuntu.

**Comment by draske79** [comment]
Hi there,

I have some additional info. The issue looks like #57. But ram is not the issue on the system:

free -m
              total        used        free      shared  buff/cache   available
Mem:          16038         101       15679          11         257       15648
Swap:          3904           0        3904

I tried the 2GB version of elasticsearch without avail (gives a different error, probably out of memory).

Docker command gives the following:

malice@localhost:~$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
>                 -v `pwd`:/malice/samples \
>                 -e MALICE_VT_API=$MALICE_VT_API \
>                 malice/engine -D scan ccsetup539.exe
DEBU[0000] Malice config loaded from: /malice/config/config.toml
DEBU[0000] config.toml version: v0.3.2, malice version: dev
DEBU[0000] Malice plugins loaded from plugins/bindata.go
DEBU[0000] Using 8 PROCS
DEBU[0000] Malice Version: dev, commit none, built at unknown
DEBU[0000] Running inside Docker...
DEBU[0000] Connected to docker daemon client             ip=localhost port=2375
DEBU[0000] Searching for container: malice-elastic       env=development
DEBU[0000] name:  malice-elastic   container.Name:  hungry_newton
DEBU[0000] MATCH:  false
DEBU[0000] name:  malice-elastic   container.Name:  malice-elastic
DEBU[0000] MATCH:  true
DEBU[0000] Container FOUND: malice-elastic               env=development
DEBU[0000] Elasticsearch is running.                     image="malice/elasticsearch" ip= network=default
DEBU[0000] Attempting to PING to: http://elasticsearch:9200
ERRO[0000] "Get http://elasticsearch:9200/: dial tcp: lookup elasticsearch on 85.17.150.123:53: no such host"
goroutine 1 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0x563fd4ae08c0, 0xc420436540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x92
github.com/maliceio/malice/malice/errors.CheckError(0x563fd4ae08c0, 0xc420436540, 0x0)
        /go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x64
github.com/maliceio/malice/malice/database/elasticsearch.InitElasticSearch(0x0, 0x0, 0x1, 0x1)
        /go/src/github.com/maliceio/malice/malice/database/elasticsearch/elasticsearch.go:124 +0x6a
github.com/maliceio/malice/commands.ScanSample(0x7ffd78327f39, 0xe)
        /go/src/github.com/maliceio/malice/commands/scan.go:58 +0x45e
github.com/maliceio/malice/commands.cmdScan(0x7ffd78327f39, 0xe, 0x0, 0xc42033a000, 0x0)
        /go/src/github.com/maliceio/malice/commands/scan.go:22 +0x37
github.com/maliceio/malice/commands.glob..func1(0xc4202e1900, 0x0, 0xc4202e1900)
        /go/src/github.com/maliceio/malice/commands/commands.go:25 +0x8c
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x563fd4724660, 0x563fd4807de8, 0xc4202e1900, 0xc42033a000, 0x0)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd6
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0x563fd43c213b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x563fd43c5eea, 0xb, 0x0, ...)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb98
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc42009f860, 0xc42000c180, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x814
main.main()
        /go/src/github.com/maliceio/malice/main.go:88 +0x54a


2018/03/18 09:28:39 Head http://elasticsearch:9200/malice: dial tcp: lookup elasticsearch on 85.17.150.123:53: no such host

RUnning scan in debug as follow:

malice@localhost:~$ malice -D scan ccsetup539.exe
DEBU[0000] Malice config loaded from: /home/malice/.malice/config/config.toml
DEBU[0000] config.toml version: v0.3.11, malice version: 0.3.11
DEBU[0000] Malice plugins loaded from: /home/malice/.malice/plugins/plugins.toml
DEBU[0000] Using 8 PROCS
DEBU[0000] Malice Version: 0.3.11, commit 9e7f91e08345f227b4ddfe3690bc5ee52d1c6feb, built at 2017-07-22T23:52:36Z
DEBU[0000] Running inside Docker...
DEBU[0000] Connected to docker daemon client             ip=localhost port=2375
DEBU[0000] Searching for container: malice-elastic       env=development
DEBU[0000] name:  malice-elastic   container.Name:  malice-elastic
DEBU[0000] MATCH:  true
DEBU[0000] Container FOUND: malice-elastic               env=development
DEBU[0000] Elasticsearch is running.                     image="malice/elasticsearch" ip= network=default
DEBU[0000] Attempting to PING to: http://localhost:9200
ERRO[0000] "Get http://localhost:9200/: dial tcp [::1]:9200: getsockopt: connection refused"
goroutine 1 [running]:
github.com/maliceio/malice/malice/errors.CheckErrorWithMessage(0xdf02a0, 0xc4203bb500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:24 +0x7d
github.com/maliceio/malice/malice/errors.CheckError(0xdf02a0, 0xc4203bb500, 0x428000)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/errors/errors.go:12 +0x62
github.com/maliceio/malice/malice/database/elasticsearch.InitElasticSearch(0x0, 0x0, 0x1, 0x1)
        /Users/user/src/go/src/github.com/maliceio/malice/malice/database/elasticsearch/elasticsearch.go:124 +0x68
github.com/maliceio/malice/commands.ScanSample(0x7ffc63a51822, 0xe)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:58 +0x46f
github.com/maliceio/malice/commands.cmdScan(0x7ffc63a51822, 0xe, 0x0, 0xc42036e000, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/scan.go:22 +0x35
github.com/maliceio/malice/commands.glob..func1(0xc4202e7680, 0x0, 0xc4202e7680)
        /Users/user/src/go/src/github.com/maliceio/malice/commands/commands.go:25 +0x8a
github.com/maliceio/malice/vendor/github.com/urfave/cli.HandleAction(0x9c9220, 0xade028, 0xc4202e7680, 0xc42036e000, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/maliceio/malice/vendor/github.com/urfave/cli.Command.Run(0xab9204, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xabcf9f, 0xb, 0x0, ...)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/maliceio/malice/vendor/github.com/urfave/cli.(*App).Run(0xc4202d09c0, 0xc42000e180, 0x4, 0x4, 0x0, 0x0)
        /Users/user/src/go/src/github.com/maliceio/malice/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
        /Users/user/src/go/src/github.com/maliceio/malice/main.go:88 +0x584


2018/03/18 09:24:19 Head http://localhost:9200/malice: dial tcp [::1]:9200: getsockopt: connection refused

Pinging localhost:9200 gives":
ping: unknown host localhost:9200

docker logs:

malice@localhost:~$ docker logs malice-elastic
[2018-03-18T09:14:23,223][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-18T09:14:23,389][INFO ][o.e.e.NodeEnvironment    ] [5sDgi4Q] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda3)]], net usable_space [851.5gb], net total_space [908.8gb], types [ext4]
[2018-03-18T09:14:23,390][INFO ][o.e.e.NodeEnvironment    ] [5sDgi4Q] heap size [7.9gb], compressed ordinary object pointers [true]
[2018-03-18T09:14:23,392][INFO ][o.e.n.Node               ] node name [5sDgi4Q] derived from node ID [5sDgi4QaQTyyHSwQbTfZ5A]; set [node.name] to override
[2018-03-18T09:14:23,392][INFO ][o.e.n.Node               ] version[6.0.0], pid[1], build[8f0685b/2017-11-10T18:41:22.859Z], OS[Linux/4.4.0-116-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2018-03-18T09:14:23,392][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Xms8g, -Xmx8g, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config]
[2018-03-18T09:14:24,498][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [aggs-matrix-stats]
[2018-03-18T09:14:24,498][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [analysis-common]
[2018-03-18T09:14:24,498][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [ingest-common]
[2018-03-18T09:14:24,498][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [lang-expression]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [lang-mustache]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [lang-painless]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [parent-join]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [percolator]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [reindex]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [repository-url]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [transport-netty4]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] loaded module [tribe]
[2018-03-18T09:14:24,499][INFO ][o.e.p.PluginsService     ] [5sDgi4Q] no plugins loaded
[2018-03-18T09:14:26,045][INFO ][o.e.d.DiscoveryModule    ] [5sDgi4Q] using discovery type [zen]
[2018-03-18T09:14:27,010][INFO ][o.e.n.Node               ] initialized
[2018-03-18T09:14:27,010][INFO ][o.e.n.Node               ] [5sDgi4Q] starting ...
[2018-03-18T09:14:27,197][INFO ][o.e.t.TransportService   ] [5sDgi4Q] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2018-03-18T09:14:27,211][INFO ][o.e.b.BootstrapChecks    ] [5sDgi4Q] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2018-03-18T09:14:30,277][INFO ][o.e.c.s.MasterService    ] [5sDgi4Q] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {5sDgi4Q}{5sDgi4QaQTyyHSwQbTfZ5A}{aIQFDYxrSeWY_TmMu0keIQ}{172.17.0.2}{172.17.0.2:9300}
[2018-03-18T09:14:30,283][INFO ][o.e.c.s.ClusterApplierService] [5sDgi4Q] new_master {5sDgi4Q}{5sDgi4QaQTyyHSwQbTfZ5A}{aIQFDYxrSeWY_TmMu0keIQ}{172.17.0.2}{172.17.0.2:9300}, reason: apply cluster state (from master [master {5sDgi4Q}{5sDgi4QaQTyyHSwQbTfZ5A}{aIQFDYxrSeWY_TmMu0keIQ}{172.17.0.2}{172.17.0.2:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-03-18T09:14:30,314][INFO ][o.e.h.n.Netty4HttpServerTransport] [5sDgi4Q] publish_address {172.17.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2018-03-18T09:14:30,314][INFO ][o.e.n.Node               ] [5sDgi4Q] started
[2018-03-18T09:14:30,368][INFO ][o.e.g.GatewayService     ] [5sDgi4Q] recovered [0] indices into cluster_state
[2018-03-18T09:16:17,695][INFO ][o.e.n.Node               ] [5sDgi4Q] stopping ...
[2018-03-18T09:16:17,716][INFO ][o.e.n.Node               ] [5sDgi4Q] stopped
[2018-03-18T09:16:17,716][INFO ][o.e.n.Node               ] [5sDgi4Q] closing ...
[2018-03-18T09:16:17,727][INFO ][o.e.n.Node               ] [5sDgi4Q] closed

Docker ps -a (note the exited (143) !!!):

docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                        PORTS                  NAMES
48ac05fd390b        malice/elasticsearch   "/elastic-entrypoint…"   15 minutes ago      Exited (143) 13 minutes ago                          malice-elastic
ffdbd1d97c4a        malice/kibana:5.5      "/docker-entrypoint.…"   13 hours ago        Created                       0.0.0.0:80->5601/tcp   malice-kibana

The Elasticsearch website report this is an access issue, but I am not sure where to change the access
https://discuss.elastic.co/t/i-am-getting-an-error-when-i-tried-to-restart-elasticsearch-service/44726/6

I hope this helps

**Comment by blacktop** [comment]
The Docker-IN-Docker version of malice is currently broken.  Did you also try the binary or deb install?

**Comment by blacktop** [comment]
Did you run this part?
```
echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w vm.max_map_count=262144
```

**Comment by blacktop** [comment]
It really sounds like ES is running out of memory.  I wonder if Docker is somehow limiting the mem that the container has?

**Comment by draske79** [comment]
Hi there, thanks for all the feedback :)
I have installed malice using the instructions on https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md:

$ wget https://github.com/maliceio/malice/releases/download/v0.3.11/malice_0.3.11_linux_amd64.tar.gz -O /tmp/malice.tar.gz
$ sudo tar -xzf /tmp/malice.tar.gz -C /usr/local/bin/

And  I did run:

echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w vm.max_map_count=262144

The only issue during installation is the fact that this does not work on 16.04:

**Comment by draske79** [comment]
Hi there,

I tried all steps on the link, without avail. However I found another workaround which works.

After a restart I run Docker ps -a, take the ID for elasticsearch and give a reboot command 
example:
docker restart b3bcb565eb2d

The ps -a command now report the task running:

b3bcb565eb2d        malice/elasticsearch:5.5   "/elastic-entrypoint…"   9 minutes ago        Up About a minute               0.0.0.0:9200->9200/tcp, 9300/tcp   malice-elastic

And the scan runs fine.

I get the same result if I remove the closed docker containers.

My suspicious is looking at the exit times, that the restart command of the server somehow crashes elasticsearch. Malice seems not to restart it until the closed docker is removed. 

For now I will place a small script in my reboot sequence that runs:
docker rm $(docker ps -a -q)

This will close all exited dockers. Would it be an idea that this check is added to malice ?

**Comment by blacktop** [comment]
if you delete the elasticsearch container you lose all the data?

**Comment by draske79** [comment]
Good point. I currently do not use the data. I make a scan, dump it to file and process this. I will check and let you know. Probably a docker restart is a more graceful solution :)

**Comment by draske79** [comment]
As far as I can see, indeed the data is lost (unless you commit the changes to the image, but this is not a help). As far as I can see as well the elasticsearch does not crash at all, unless there is a reboot.
I assume malice checks if the container exist, and if not creates it. It would be nice if it checks if it is up and running, and if not (re)start it. Now it just produces an error. I have seen the same when the AVG crasht and and all follow up scans provided errors. 
Beside that everything works fine :)

**Comment by blacktop** [comment]
I intend on adding a lot more checks around elasticsearch and allow people to supply their own and not use `malice/elasticsearch` as well as support for using other databases if the user wants.
