### ISSUE TITLE
FEATURE REQUEST: Custom timeout elasticsearch and disable install of plugins

### ISSUE THREAD

**Issue by draske79** [maliceio/malice#73]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------
If I disable plugins in the plugin.toml file that the plugins do not get downloaded or updated with malice plugin update -all. This would save time and diskspace.

Thanks !!!

**Comment by blacktop** [comment]
This should work? 

https://github.com/maliceio/malice/blob/master/config/config.toml#L33

**Comment by blacktop** [comment]
please see #80
