### ISSUE TITLE
Custom timeout before elastic search is online

### ISSUE THREAD

**Issue by draske79** [maliceio/malice#75]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------
Would it be possible to get a custom timeout for elastic search coming online ? It is 20 seconds now. it seems on my system sometimes more time is needed

**Comment by blacktop** [comment]
Can you try https://github.com/maliceio/malice/blob/master/config/config.toml#L33

**Comment by blacktop** [comment]
please see #80
