### ISSUE TITLE
Demo doesn't login

### ISSUE THREAD

**Issue by jeffg2k** [maliceio/malice#76]
Demo doesn't login.  Says "Oops! Error. Try again."

> DEMO: demo.malice.io
> 
> username: malice
> password: ecilam

**Comment by blacktop** [comment]
fixed it!  not sure why it broke, somebody must be 'hacking' it 😏 

Thank you for letting me know! 👍

**Comment by yalpanian** [comment]
same story now ..

**Comment by blacktop** [comment]
https://github.com/elastic/kibana/issues/29093

**Comment by blacktop** [comment]
fixed... again 😞

**Comment by co-devs** [comment]
same story again...

**Comment by blacktop** [comment]
fixed... again 😞

**Comment by blacktop** [comment]
Created a cronjob to rest it every 5 mons so we should be good now 😏
