### ISSUE TITLE
WEBUI not starting properly

### ISSUE THREAD

**Issue by boistordu** [maliceio/malice#78]
**Describe the bug**
I got an elastic presentation page, nothing else

**To Reproduce**

run malice elk on macos X, malice 0,3,24
**Expected behavior**

having the page giving in the screenshot from the wikipage
**Environment (please complete the following information):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 33IC:TYMG:FLK6:NHUZ:QJCU:RD7R:5OOJ:NIBY:PSBG:MAPS:GEGL:3RDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 46
 Goroutines: 74
 System Time: 2018-11-17T15:42:50.598099279Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, Docker For Mac, Docker Toolbox, docker-machine, etc.):**
docker for mac and virtualbox present
**Additional context**
![screen shot 2018-11-17 at 16 39 19](https://user-images.githubusercontent.com/9523075/48662812-9a98f480-ea87-11e8-8a20-b434fe47884a.png)

**Comment by blacktop** [comment]
what is your config.toml? in ~/.malice/config/config.toml ?

**Comment by blacktop** [comment]
I did a lot of fixes/reworkin of ELK images this weekend.  If you do a

```bash
docker pull malice/elasticsearch:6.4
docker pull malice/kibana:6.4
```

It should fix it for you.

Make sure you remove those old images

```
docker rm -f malice-elastic malice-kibana
```

**Comment by boistordu** [comment]
okey so I've upgraded it. 
Something is taking way more cpu than before when creating malice-elastic `FATA[0023] failed to start to database: connecting to elasticsearch timed out after 20 seconds: failed to ping elasticsearch: Get http://localhost:9200/: EOF`
I always need to start twice.
to answer to your previous question, I didn't change anything to the configuration file "didn't know that I had to ?" 


```

#######################################################################
# MALICE Configuration ################################################
#######################################################################

title = "Malice Runtime Configuration"
version = "v0.3.24"

[author]
  name = "blacktop"
  organization = "MaliceIO"

[web]
  url = "0.0.0.0:80"
  admin_url = "127.0.0.1:3333"

[email]
  host = "smtp.example.com"
  port = 25
  user = "username"
  pass = "password"

[database]
  name = "malice-elastic"
  image = "malice/elasticsearch:6.4"
  url = "http://localhost:9200"
  # url = "http://elasticsearch:9200"
  username = ""
  password = ""
  ports = [9200]
  timeout = 20
  enabled = true

[ui]
  name = "malice-kibana"
  image = "malice/kibana:6.4"
  server = "localhost"
  ports = [443]
  enabled = true

[environment]
  run = "development"

[docker]
  machine-name = "malice"
  endpoint = "tcp://localhost:2376"
  timeout = 120
  binds = "malice:/malware:ro"
  links = "malice-elastic:elasticsearch"
  cpu = 500000000
  memory = 524288000

[logger]
  filename = "malice.log"
  maxsize = 10
  maxage = 30
  maxbackups = 7
  localtime = false

[proxy]
  enable = false
  http = ""
  https = ""
```

**Comment by blacktop** [comment]
did you remove the running containers?

**Comment by blacktop** [comment]
also what does this cmd output:

```
$ docker logs -f malice-elastic
```

**Comment by blacktop** [comment]
I was able to also experience problems with elasticsearch:6.4 so I have upgraded the config to use 6.5 now.  Can you let me know if that fixes it for you?

**Comment by blacktop** [comment]
If the new release doesn't fix your issue, please re-open.  Thank you for your contribution! 👍 

https://github.com/maliceio/malice/releases

**Comment by blacktop** [comment]
if you upgrade malice it should ask you to "upgrade" your local config too `~/.malice/config/config.toml` but I haven't tested that feature a lot so it might not auto replace it properly, if it doesn't you can just `rm -rf ~/.malice` and remove the whole config folder and try again.

**Comment by boistordu** [comment]
okey yeah so it was the 6.5 version the solution. thanks
